sudo: false
language: node_js
node_js:
- '0.12'
- '4'
- '6'
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: Kknbo+hTq34Qh3NZtqRuAgQgh+n/hhwj97zld2jNE+Fmdke/8mf5FqudGu4jlZzX5VGg4ByxdMlzNdTJMOvzE20L7EmYxAhBuvnyH9fJDpzbbA/z6Kxqxr4xsFdT8Gcn6HRXtgbQ1rCePhBMwNh29muVr//MRE1fp9nx7pvt0oY=
  email:
    recipients:
      secure: GVkX5mi+Hk97yWyUtnpFxKmBMzyeJGJAAShN61rz/cZ0q9TUEASofUo44fRWhyldFXaRZ6lyOfbT4F4a/sF0AIlhcuQzzPumLwcQkmWHeUPTFOwO6UF3zT+ENM8e33dy2f5Ce17DjkPsfpWGU588os8SZt4MsO5UeoSKLVtYAYQ=
