sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '8'
- '9'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '0.8'
  - node_js: '0.10'
  - node_js: '9'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/8f936db45f9b4904e2d47179c7426af79bd59b86/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/8f936db45f9b4904e2d47179c7426af79bd59b86/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/8f936db45f9b4904e2d47179c7426af79bd59b86/scripts/node-publish.bash)"
notifications:
  slack:
    secure: gzGdEZAa9M99fVU1q+V8hyEi8dn4X/MAjCCRhzb3wHrwr1g9BducD2U6PBDr3GqAVGung62I/sD9+O0Vl2hlhjGMy7UriBFuKn0aC7g/uOC91Pd7NkNtpMQIxdKBbSC6qasUc+RZeLuZsZFz3CeaxREJaK7epRs8KKXZZuZV2JU=
  email:
    recipients:
      secure: h/Jv9euL9A3JgpXSr9QBITV3DnSNE4m+N6wgKtMSz6YPTtgd6N+Sy/Vv1eF48xU/pYpb/CdOuWr21DzuBrVc3ZqDpYmqvVARKIKNer6Z0HkYY5Fq9visZLlxFDEkhi2H0xtASNKwSO7Ch+8cQVZFv7UQCofqHY330jMZFzhSKWQ=
